todo/urls.py
from django.urls import path

from todo.views import (
    index,
    TaskListView,
    TaskCreateView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    toggle_complete_task,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TagDetailView,
    WorkerDeleteView,
    WorkerDetailView,
    WorkerCreateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/<int:pk>/toggle-complete/", toggle_complete_task, name="task-toggle-complete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo_list"

todo_settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo_list")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Worker(AbstractUser):
    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return (
            f"{self.username} "
            f"({self.first_name} {self.last_name})"
        )

    def get_absolute_url(self):
        return reverse("todo_list:worker-detail", kwargs={"pk": self.pk})


class Task(models.Model):
    name = models.CharField(max_length=63)
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    status = models.BooleanField()
    tags = models.ManyToManyField("Tag", related_name="tasks")

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.name


class Tag(models.Model):
    objects = None
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from todo.models import Tag, Task, Worker


class TaskNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "class": "form-list-find",
            "placeholder": "Search by name"
        }),
    )


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = [
            "name",
            "content",
            "deadline",
            "status",
            "tags"
        ]

    deadline = forms.DateTimeField(
        label='What is deadline?',
        widget=forms.SelectDateWidget
    )


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker

todo/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskNameSearchForm, TaskForm, WorkerCreationForm
from todo.models import Task, Tag, Worker


@login_required
def index(request):
    queryset = Task.objects.prefetch_related("tags")
    num_tasks = queryset.count()
    num_finished_tasks = queryset.filter(status=True).count()
    num_unfinished_tasks = queryset.filter(status=False).count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_tasks": num_tasks,
        "num_finished_tasks": num_finished_tasks,
        "num_unfinished_tasks": num_unfinished_tasks,
        "num_visits": num_visits + 1,
    }

    return render(request, "todo/index.html", context)


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "todo/task_list.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskNameSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Task.objects.prefetch_related("tags")
        form = TaskNameSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:task-list")


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:task-list")


@login_required
def toggle_complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.status = not task.status
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo_list:task-list"))


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDetailView(LoginRequiredMixin, generic.DetailView):
    model = Tag


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.prefetch_related("tasks")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("todo_list:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>ToDo Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>
</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">next page</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next page</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a>
        href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a
        href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a
        href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
  {% endif %}
  <li class="list-group-item"><a href="{% url 'todo_list:index' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'todo_list:task-list' %}">Tasks</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'todo_list:tag-list' %}">Tags</a>
  </li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
    <h1>TODO Service</h1>
    <p>Welcome to TODO Service</p>
    <h2>Dynamic content</h2>
    <p>The TODO service has the following record counts:</p>
    <ul>
        <li><strong>All tasks:</strong> {{ num_tasks }}</li>
        <li><strong>Finished tasks:</strong> {{ num_finished_tasks }}</li>
        <li><strong>Unfinished tasks:</strong> {{ num_unfinished_tasks }}</li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:tag-list' %}" class="btn btn-success">No</a>
  </form>
{% endblock %}

templates/todo/tag_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ tag.name }}
  </h1>
  <a href="{% url 'todo_list:tag-delete' pk=tag.id %}"
     class="btn btn-danger link-to-page">
    Delete
  </a>

  <a href="{% url 'todo_list:tag-update' pk=tag.id %}"
     class="btn btn-secondary link-to-page">
    Update
  </a>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tag list
    <a href="{% url 'todo_list:tag-create' %}"
       class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>
  <br>

  {% if tag_list %}

    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo_list:tag-update' pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'todo_list:tag-delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no task in the service.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:task-list' %}" class="btn btn-success">No</a>
  </form>
{% endblock %}

templates/todo/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ task.name }}
  </h1>
  <a href="{% url 'todo_list:task-delete' pk=task.id %}"
     class="btn btn-danger link-to-page">
    Delete
  </a>

  <a href="{% url 'todo_list:task-update' pk=task.id %}"
     class="btn btn-secondary link-to-page">
    Update
  </a>
  <p>Content: {{ task.content }}</p>
  <p>Deadline: {{ task.deadline }}</p>

  <hr>
  <ul>
    {% for tag in task.tags.all %}
      <li>{{ tag.id }} {{ tag.name }}</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo_list:task-create' %}"
       class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>
  <br>

  {% if task_list %}

    {% for task in task_list %}
      <p>
      <h4>{{ task.name }}:
        {% if task.status %}
          <img src="{% static 'img/complete.png' %}" alt=""
               width="30"/>
        {% else %}
          <img src="{% static 'img/incomplete.png' %}" alt=""
               width="30"/>
        {% endif %}
        {% if task.status %}
          <a href="{% url 'todo_list:toggle-complete-task' pk=task.id %}"
             class="btn btn-danger link-to-page">
            Undo
          </a>
        {% else %}
          <a href="{% url 'todo_list:toggle-complete-task' pk=task.id %}"
             class="btn btn-success link-to-page">
            Complete
          </a>
        {% endif %}
      </h4>
      <p><strong>{{ task.content }}</strong></p>
      <p>
        Created: {{ task.created_at }}
        {% if not task.status %}
          Deadline: {{ task.deadline }}
        {% endif %}
      </p>
      <p>Tags:
        {% for tag in task.tags.all %}
          {{ tag.name }}
        {% endfor %}
        <a href="{% url 'todo_list:task-update' pk=task.id %}"
           class="manage-task-tags">Update</a>
        <a href="{% url 'todo_list:task-delete' pk=task.id %}"
           class="manage-task-tags">Delete</a>
      </p>

      <hr>
    {% endfor %}
  {% endif %}
{% endblock %}